// Default templates (no contact data). Variables in {{double braces}} are filled from the selected owner/property/requirement.
export const VARS = ['owner_name', 'owner_entity', 'owner_mailing', 'property_address', 'property_city', 'building_sf', 'land_acres', 'year_built', 'requirement_name', 'requirement_sf', 'requirement_area', 'broker_name', 'broker_company', 'broker_phone', 'broker_email', 'today'];
export const DEFAULT_TEMPLATES = [
  { id: 't_call', kind: 'Call script', name: 'Owner intro call', subject: '', body: "Hi {{owner_name}}, this is {{broker_name}} with {{broker_company}}. I specialize in industrial property around {{property_city}}, and I'm calling about your building at {{property_address}}.\n\nI'm not calling with a listing pitch. I work with owner-users and investors who are looking for buildings like yours, and some would talk about an off-market deal. Have you thought about what the property would be worth today, or what your plans are for it over the next couple of years?\n\n[If no: ask if a short value summary would be useful and get the best email.]\n[If yes: set a time to walk the building.]" },
  { id: 't_email_intro', kind: 'Email', name: 'Off-market inquiry (owner)', subject: 'Your property at {{property_address}}', body: "Hi {{owner_name}},\n\nI'm {{broker_name}} with {{broker_company}}. I focus on industrial property in the {{property_city}} area.\n\nI'm reaching out about {{property_address}} ({{building_sf}} SF). I work with buyers who are looking for this type of building and would consider a private, off-market sale if the timing and price were right for you.\n\nWould you be open to a short call? Even if selling isn't on your radar, I'm happy to share what similar buildings have traded for recently.\n\nBest,\n{{broker_name}}\n{{broker_phone}} | {{broker_email}}" },
  { id: 't_email_req', kind: 'Email', name: 'Buyer/tenant requirement match', subject: 'A buyer looking for a building like {{property_address}}', body: "Hi {{owner_name}},\n\nI'm working with a qualified client looking for about {{requirement_sf}} SF in the {{requirement_area}} area, and your property at {{property_address}} could be a good fit.\n\nThis would be a private conversation with no listing and no obligation. Do you have 10 minutes this week?\n\n{{broker_name}}\n{{broker_company}} | {{broker_phone}}" },
  { id: 't_fu', kind: 'Email', name: 'Follow-up after call', subject: 'Following up: {{property_address}}', body: "Hi {{owner_name}},\n\nThanks for taking my call. As promised, I'll put together a short summary of recent industrial sales and leases near {{property_address}}.\n\nIf anything changes with your plans for the building, I'm here.\n\n{{broker_name}}\n{{broker_phone}}" },
  { id: 't_sms', kind: 'Text', name: 'Short text after voicemail', subject: '', body: "Hi {{owner_name}}, it's {{broker_name}} ({{broker_company}}). I just left you a voicemail about {{property_address}}. I have buyers looking in {{property_city}}. Is a quick call this week OK?" },
  { id: 't_letter', kind: 'Letter', name: 'Owner letter (off-market)', subject: '', body: "{{today}}\n\n{{owner_entity}}\n{{owner_mailing}}\n\nRe: {{property_address}}, {{property_city}}, Illinois\n\nDear {{owner_name}},\n\nMy name is {{broker_name}}, and I am an industrial real estate broker with {{broker_company}}. I'm writing about your property at {{property_address}}.\n\nDemand for well-located industrial buildings in the {{property_city}} area remains strong, and I am working with owner-users and investors who would consider buying a property like yours privately, without a public listing.\n\nIf you have ever thought about selling, refinancing, or simply knowing what your building is worth today, I would welcome a confidential conversation. There is no cost or obligation.\n\nYou can reach me directly at {{broker_phone}} or {{broker_email}}.\n\nSincerely,\n\n\n{{broker_name}}\n{{broker_company}}" },
];
